// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SARE.Infrastructure.Persistence;

#nullable disable

namespace SARE.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SARE.Domain.Cart.Cart", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<short?>("BatteryPct")
                        .HasColumnType("smallint")
                        .HasColumnName("battery_pct");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SwVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sw_version");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_carts");

                    b.ToTable("carts", null, t =>
                        {
                            t.HasCheckConstraint("ck_carts_battery_pct", "battery_pct IS NULL OR battery_pct BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_carts_status", "status IN ('active', 'disabled')");
                        });
                });

            modelBuilder.Entity("SARE.Domain.Cart.DetectionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float?>("Confidence")
                        .HasColumnType("real")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DetectedBarcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("detected_barcode");

                    b.Property<string>("FinalBarcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("final_barcode");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid?>("SessionItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_item_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<int>("WeightDeltaG")
                        .HasColumnType("integer")
                        .HasColumnName("weight_delta_g");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone");

                    b.HasKey("Id")
                        .HasName("pk_detection_events");

                    b.HasIndex("SessionItemId")
                        .HasDatabaseName("ix_detection_events_session_item_id");

                    b.HasIndex("SessionId", "CreatedAt")
                        .HasDatabaseName("ix_detection_events_session_id_created_at");

                    b.ToTable("detection_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_detection_events_confidence", "confidence IS NULL OR confidence BETWEEN 0 AND 1");

                            t.HasCheckConstraint("ck_detection_events_outcome", "outcome IN ('accepted', 'corrected', 'rejected', 'unknown')");

                            t.HasCheckConstraint("ck_detection_events_source", "source IN ('vision', 'scanner', 'manual')");

                            t.HasCheckConstraint("ck_detection_events_zone", "zone IN ('basket', 'tray')");
                        });
                });

            modelBuilder.Entity("SARE.Domain.Cart.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cart_id");

                    b.Property<string>("CloseReason")
                        .HasColumnType("text")
                        .HasColumnName("close_reason");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by");

                    b.Property<DateTime>("LastActivityAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TotalMinor")
                        .HasColumnType("integer")
                        .HasColumnName("total_minor");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("CartId")
                        .HasDatabaseName("ix_sessions_cart_id");

                    b.HasIndex("ClosedBy")
                        .HasDatabaseName("ix_sessions_closed_by");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sessions_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sessions_user_id");

                    b.ToTable("sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_sessions_close_reason", "close_reason IS NULL OR close_reason IN ('staff_closed', 'abandoned')");

                            t.HasCheckConstraint("ck_sessions_closed_at", "closed_at IS NULL OR closed_at >= started_at");

                            t.HasCheckConstraint("ck_sessions_status", "status IN ('open', 'closed', 'abandoned')");

                            t.HasCheckConstraint("ck_sessions_total_minor", "total_minor >= 0");
                        });
                });

            modelBuilder.Entity("SARE.Domain.Cart.SessionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<int>("UnitPriceMinor")
                        .HasColumnType("integer")
                        .HasColumnName("unit_price_minor");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone");

                    b.HasKey("Id")
                        .HasName("pk_session_items");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_session_items_session_id");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("ix_session_items_variant_id");

                    b.ToTable("session_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_session_items_removed_at", "removed_at IS NULL OR removed_at >= added_at");

                            t.HasCheckConstraint("ck_session_items_source", "source IN ('vision', 'scanner', 'manual')");

                            t.HasCheckConstraint("ck_session_items_unit_price_minor", "unit_price_minor >= 0");

                            t.HasCheckConstraint("ck_session_items_zone", "zone IN ('basket', 'tray')");
                        });
                });

            modelBuilder.Entity("SARE.Domain.Cart.ShelfEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsMatched")
                        .HasColumnType("boolean")
                        .HasColumnName("is_matched");

                    b.Property<Guid?>("MatchedSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_session_id");

                    b.Property<string>("ShelfId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("shelf_id");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<int>("WeightDeltaG")
                        .HasColumnType("integer")
                        .HasColumnName("weight_delta_g");

                    b.HasKey("Id")
                        .HasName("pk_shelf_events");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_shelf_events_created_at");

                    b.HasIndex("MatchedSessionId")
                        .HasDatabaseName("ix_shelf_events_matched_session_id");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("ix_shelf_events_variant_id");

                    b.ToTable("shelf_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_shelf_events_matched_session", "NOT is_matched OR matched_session_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("SARE.Domain.Catalog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("SARE.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name_en");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("SARE.Domain.Catalog.ProductOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_product_options");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_options_product_id");

                    b.ToTable("product_options", (string)null);
                });

            modelBuilder.Entity("SARE.Domain.Catalog.ProductOptionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_option_id");

                    b.Property<string>("ValueAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value_ar");

                    b.Property<string>("ValueEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value_en");

                    b.HasKey("Id")
                        .HasName("pk_product_option_values");

                    b.HasIndex("ProductOptionId")
                        .HasDatabaseName("ix_product_option_values_product_option_id");

                    b.ToTable("product_option_values", (string)null);
                });

            modelBuilder.Entity("SARE.Domain.Catalog.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("barcode");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("PriceMinor")
                        .HasColumnType("integer")
                        .HasColumnName("price_minor");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("WeightG")
                        .HasColumnType("integer")
                        .HasColumnName("weight_g");

                    b.HasKey("Id")
                        .HasName("pk_product_variants");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_product_variants_barcode");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_variants_product_id");

                    b.ToTable("product_variants", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_variants_barcode", "length(trim(barcode)) > 0");

                            t.HasCheckConstraint("ck_product_variants_price_minor", "price_minor >= 0");

                            t.HasCheckConstraint("ck_product_variants_weight_g", "weight_g > 0");
                        });
                });

            modelBuilder.Entity("SARE.Domain.Catalog.VariantOptionValue", b =>
                {
                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<Guid>("OptionValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_value_id");

                    b.HasKey("VariantId", "OptionValueId")
                        .HasName("pk_variant_option_values");

                    b.HasIndex("OptionValueId")
                        .HasDatabaseName("ix_variant_option_values_option_value_id");

                    b.ToTable("variant_option_values", (string)null);
                });

            modelBuilder.Entity("SARE.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NfcUid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("nfc_uid");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("NfcUid")
                        .IsUnique()
                        .HasDatabaseName("ix_users_nfc_uid");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('customer', 'staff', 'admin')");
                        });
                });

            modelBuilder.Entity("SARE.Domain.Cart.DetectionEvent", b =>
                {
                    b.HasOne("SARE.Domain.Cart.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detection_events_sessions_session_id");

                    b.HasOne("SARE.Domain.Cart.SessionItem", null)
                        .WithMany()
                        .HasForeignKey("SessionItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_detection_events_session_items_session_item_id");
                });

            modelBuilder.Entity("SARE.Domain.Cart.Session", b =>
                {
                    b.HasOne("SARE.Domain.Cart.Cart", null)
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_carts_cart_id");

                    b.HasOne("SARE.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ClosedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sessions_users_closed_by");

                    b.HasOne("SARE.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sessions_users_user_id");
                });

            modelBuilder.Entity("SARE.Domain.Cart.SessionItem", b =>
                {
                    b.HasOne("SARE.Domain.Cart.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_items_sessions_session_id");

                    b.HasOne("SARE.Domain.Catalog.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_items_product_variants_variant_id");
                });

            modelBuilder.Entity("SARE.Domain.Cart.ShelfEvent", b =>
                {
                    b.HasOne("SARE.Domain.Cart.Session", null)
                        .WithMany()
                        .HasForeignKey("MatchedSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_shelf_events_sessions_matched_session_id");

                    b.HasOne("SARE.Domain.Catalog.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shelf_events_product_variants_variant_id");
                });

            modelBuilder.Entity("SARE.Domain.Catalog.Product", b =>
                {
                    b.HasOne("SARE.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");
                });

            modelBuilder.Entity("SARE.Domain.Catalog.ProductOption", b =>
                {
                    b.HasOne("SARE.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_options_products_product_id");
                });

            modelBuilder.Entity("SARE.Domain.Catalog.ProductOptionValue", b =>
                {
                    b.HasOne("SARE.Domain.Catalog.ProductOption", null)
                        .WithMany()
                        .HasForeignKey("ProductOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_option_values_product_options_product_option_id");
                });

            modelBuilder.Entity("SARE.Domain.Catalog.ProductVariant", b =>
                {
                    b.HasOne("SARE.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_variants_products_product_id");
                });

            modelBuilder.Entity("SARE.Domain.Catalog.VariantOptionValue", b =>
                {
                    b.HasOne("SARE.Domain.Catalog.ProductOptionValue", null)
                        .WithMany()
                        .HasForeignKey("OptionValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_variant_option_values_product_option_values_option_value_id");

                    b.HasOne("SARE.Domain.Catalog.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_variant_option_values_product_variants_variant_id");
                });
#pragma warning restore 612, 618
        }
    }
}
